#!/bin/sh
#
# See more info at https://www.linux-kvm.org/page/Networking
# for allowing an ordinary user to manage tunnels,
# see https://unix.stackexchange.com/questions/243382/making-dev-net-tun-available-to-qemu
# synopsis:
# 1. make sure your user is in the `netdev` group
# 2. chgrp netdev /dev/net/tun # so that the users in netdev can manage it
#
# Used by qemu to setup the TAP interface
# QEMU wants this script to be executable and located at /etc/qemu-ifup
#
# For creating tuntap interfaces on the fly, you can do:
# `sudo ip tuntap add mode tap IF-NAME`

set -x

if [ -n "$1" ]; then
    ip link del $1
    exit 0
else
    echo "Error: no interface specified"
    exit 1
fi